### Create an Event

POST http://localhost:8080/v1.0/events
Content-Type: application/json

{
  "name": "new_subscriber"
}

> {% client.test("Successful POST Request", function() {
    client.assert(response.status === 201, "Response Status is not 201")
}) %}

### Get All Events

GET http://localhost:8080/v1.0/events
Content-Type: application/json

> {% client.test("Successful GET Request", function() {
    client.assert(response.status === 200, "Response Status is not 200")
}) %}


### Event Not Found

GET http://localhost:8080/v1.0/events/b29c0c2c-a929-4253-bb5a-87a78b41727d
Content-Type: application/json

> {% client.test("Event Not Found", function() {
    client.assert(response.status === 404, "Response Status is not 404")
}) %}
